In [1]:
import numpy as np

In [2]:
lst = [2, 4, 6, 8, 13, 2020]
numpy_arr = np.array(lst)
numpy_arr

array([   2,    4,    6,    8,   13, 2020])

In [3]:
numpy_arr[1]


4

In [4]:
print(numpy_arr)

[   2    4    6    8   13 2020]


In [5]:
def np_calc(arr):
    return arr.min(),np.std(arr),np.prod(arr),np.dot(arr,arr),arr-4

arr_min,arr_std,arr_prod,arr_dot,arr_minus_four=np_calc(numpy_arr)
print(arr_min)
print("\n")
print(arr_std)
print("\n")
print(arr_prod)
print("\n")
print(arr_dot)
print("\n")
print(arr_minus_four)

2


750.3577850302851


10083840


4080689


[  -2    0    2    4    9 2016]


In [6]:
def np_calc(numpy_arr):
    return numpy_arr.min(),np.std(arr),np.prod(arr),np.dot(arr,arr),arr-4

numpy_arr,arr_std,arr_prod,arr_dot,arr_minus_four=np_calc(numpy_arr)
print(numpy_arr)

NameError: name 'arr' is not defined

In [7]:
def np_calc(numpy_arr):
    return numpy_arr.min()

numpy_arr
print(arr_min)

2
